// Helper functions for on-chain basket operations

import { Basket, BasketItem } from '@/types/basket';
import { SailsProgram } from '@/basket-market-client/lib';
import { actorIdFromAddress, fromVara } from '@/lib/varaClient';

// Types are imported from global.d.ts (generated by sails-js-cli)

/**
 * Extract on-chain basket ID from string ID
 * Returns null if not an on-chain basket
 */
export function extractOnChainBasketId(id: string): number | null {
  if (id.startsWith('onchain-')) {
    const numId = parseInt(id.replace('onchain-', ''), 10);
    return isNaN(numId) ? null : numId;
  }
  return null;
}

/**
 * Convert on-chain Basket to frontend Basket format
 * onChainBasket is the raw result from the contract (has items with poly_market_id, poly_slug, weight_bps)
 */
export function onChainBasketToFrontend(
  onChainBasket: any, // Raw on-chain basket structure
  chainId: number,
  tags: string[] = [],
  snapshot?: any
): Basket {
  // Convert on-chain items to frontend format
  // On-chain items have: poly_market_id, poly_slug, weight_bps
  const items: BasketItem[] = (onChainBasket.items || []).map((item: any) => ({
    marketId: item.poly_market_id || item.polyMarketId || '',
    slug: item.poly_slug || item.polySlug || '',
    question: item.poly_slug || item.polySlug || '', // We'll fetch this from Polymarket later
    outcome: 'YES' as const, // Default - on-chain doesn't store outcome, will be determined by user
    weightBps: Number(item.weight_bps || item.weightBps || 0),
  }));

  // Extract creator/owner - handle different formats
  let owner = '';
  if (onChainBasket.creator) {
    if (Array.isArray(onChainBasket.creator)) {
      owner = '0x' + onChainBasket.creator.map((byte: number) => 
        byte.toString(16).padStart(2, '0')
      ).join('');
    } else {
      owner = String(onChainBasket.creator);
    }
  }

  return {
    id: `onchain-${chainId}`,
    owner: owner,
    name: onChainBasket.name || '',
    description: onChainBasket.description || '',
    tags,
    createdAt: Number(onChainBasket.created_at || onChainBasket.createdAt || Date.now()),
    items,
    createdSnapshot: snapshot || {
      timestamp: Number(onChainBasket.created_at || onChainBasket.createdAt || Date.now()),
      basketIndex: 0.5, // Default - will be calculated
      components: [],
    },
    network: 'vara',
    assetKind: onChainBasket.asset_kind || onChainBasket.assetKind || 'Vara',
  };
}

/**
 * Fetch basket from on-chain
 */
export async function fetchOnChainBasket(
  program: SailsProgram,
  basketId: number
): Promise<Basket> {
  const query = program.basketMarket.getBasket(basketId);
  let result: any;
  
  // Try .call() first (standard for query methods)
  try {
    result = await query.call();
  } catch (error) {
    // Fallback to .run() if .call() fails
    console.log(`[fetchOnChainBasket] .call() failed, trying .run()...`);
    result = await query.run();
  }
  
  if ('err' in result) {
    throw new Error(result.err);
  }
  
  return result.ok;
}

/**
 * Fetch user positions from on-chain
 */
export async function fetchOnChainPositions(
  program: SailsProgram,
  userAddress: string
): Promise<Position[]> {
  const actorId = actorIdFromAddress(userAddress);
  const query = program.basketMarket.getPositions(actorId);
  
  // Try .call() first, fallback to .run()
  let positions: Position[];
  try {
    const result = await query.call();
    positions = ('ok' in result) ? result.ok : result;
  } catch (error) {
    console.log(`[fetchOnChainPositions] .call() failed, trying .run()...`);
    positions = await query.run();
  }
  
  return positions || [];
}

/**
 * Fetch settlement from on-chain
 */
export async function fetchOnChainSettlement(
  program: SailsProgram,
  basketId: number
): Promise<Settlement | null> {
  try {
    console.log(`[fetchOnChainSettlement] Fetching settlement for basket ${basketId}...`);
    const query = program.basketMarket.getSettlement(basketId);
    
    // Try .call() first (for query methods)
    let result: any;
    try {
      result = await query.call();
    } catch (callError) {
      // If .call() fails, try .run()
      console.log(`[fetchOnChainSettlement] .call() failed, trying .run()...`, callError);
      try {
        result = await query.run();
      } catch (runError) {
        console.error(`[fetchOnChainSettlement] Both .call() and .run() failed:`, runError);
        return null;
      }
    }
    
    if (!result) {
      console.log(`[fetchOnChainSettlement] No result returned for basket ${basketId}`);
      return null;
    }
    
    if ('err' in result) {
      console.log(`[fetchOnChainSettlement] Settlement query returned error for basket ${basketId}:`, result.err);
      return null; // No settlement yet
    }
    
    const settlement = result.ok || result;
    console.log(`[fetchOnChainSettlement] ✓ Successfully fetched settlement for basket ${basketId}:`, {
      status: settlement.status,
      basket_id: settlement.basket_id,
      finalized_at: settlement.finalized_at,
      proposed_at: settlement.proposed_at
    });
    
    return settlement;
  } catch (error) {
    console.error(`[fetchOnChainSettlement] Error fetching settlement for basket ${basketId}:`, error);
    return null;
  }
}

/**
 * Get user position for a specific basket
 * IMPORTANT: Uses strict equality to handle basket ID 0 correctly
 */
export function getUserPositionForBasket(
  positions: Position[],
  basketId: number
): Position | null {
  // Explicitly handle basket ID 0 - ensure proper type conversion
  const found = positions.find(p => {
    const pBasketId = typeof p.basket_id === 'bigint' ? Number(p.basket_id) : Number(p.basket_id);
    return pBasketId === basketId;
  });
  
  if (basketId === 0 && !found) {
    console.log(`[getUserPositionForBasket] No position found for basket ID 0. Available positions:`, 
      positions.map(p => ({
        basket_id: p.basket_id,
        basket_idType: typeof p.basket_id,
        basket_idNumber: typeof p.basket_id === 'bigint' ? Number(p.basket_id) : Number(p.basket_id),
        shares: p.shares
      }))
    );
  }
  
  return found || null;
}

/**
 * Calculate payout amount from settlement and position using index-based odds
 * New formula: payout = shares × (settlement_index_bps / index_at_creation_bps)
 * This allows users to profit if settlement index > index at creation
 * 
 * Edge cases handled:
 * - Settlement index = 0: User loses everything (payout = 0)
 * - Settlement index < index at creation: User loses money (payout < bet)
 * - Settlement index = index at creation: Break even (payout = bet)
 * - Settlement index > index at creation: User profits (payout > bet)
 */
export function calculatePayout(settlement: Settlement, position: Position): string {
  const shares = BigInt(String(position.shares));
  const settlementIndexBps = BigInt(String(settlement.payout_per_share)); // Settlement index in basis points (0-10000)
  
  // Get index at creation from position (new field added to contract)
  // Fallback to 10000 (100%) for backwards compatibility with old positions
  const indexAtCreationBps = position.index_at_creation_bps !== undefined 
    ? BigInt(String(position.index_at_creation_bps))
    : BigInt(10000);
  
  // Edge case: Settlement index = 0 (all items resolved NO) - user loses everything
  if (settlementIndexBps === BigInt(0)) {
    console.log('[calculatePayout] Edge case: Settlement index = 0, user loses everything');
    return '0';
  }
  
  // Validate index_at_creation_bps to prevent division by zero
  if (indexAtCreationBps === BigInt(0)) {
    console.error('[calculatePayout] Invalid index_at_creation_bps: 0, using fallback 10000');
    // Fallback: use old formula if index_at_creation is 0 (shouldn't happen with new contract)
    const payout = (shares * settlementIndexBps) / BigInt(10000);
    return fromVara(payout);
  }
  
  // New index-based payout formula: shares × (settlement_index / index_at_creation)
  const payout = (shares * settlementIndexBps) / indexAtCreationBps;
  
  // Edge case: Payout could be 0 if settlement_index < index_at_creation and shares are small
  // This is a valid outcome (user lost money), return 0
  if (payout === BigInt(0)) {
    console.log('[calculatePayout] Edge case: Calculated payout = 0 (user lost money)');
    return '0';
  }
  
  return fromVara(payout);
}

/**
 * Calculate profit/loss from payout and bet amount
 * Returns positive number for profit, negative for loss
 */
export function calculateProfitLoss(payout: string, betAmount: string): number {
  const payoutNum = parseFloat(payout);
  const betNum = parseFloat(betAmount);
  return payoutNum - betNum;
}

/**
 * Fetch all baskets from on-chain and convert to frontend format
 * This is the sustainable way to get baskets - they're stored on-chain permanently
 */
export async function fetchAllOnChainBaskets(
  program: SailsProgram,
  userAddress?: string
): Promise<Basket[]> {
  try {
    // Get total basket count
    const countQuery = program.basketMarket.getBasketCount();
    const countResult = await countQuery.call();
    const basketCount = Number(countResult);
    
    console.log(`[fetchAllOnChainBaskets] Found ${basketCount} baskets on-chain`);
    
    if (basketCount === 0) {
      return [];
    }
    
    // Fetch all baskets in parallel (with limit to avoid overwhelming)
    const fetchPromises: Promise<Basket | null>[] = [];
    for (let i = 0; i < basketCount; i++) {
      fetchPromises.push(
        program.basketMarket.getBasket(i).call()
          .then(result => {
            if ('err' in result) {
              console.warn(`[fetchAllOnChainBaskets] Basket ${i} error:`, result.err);
              return null;
            }
            
            const onChainBasket = result.ok;
            // Convert ActorId to hex string for creator
            let creatorHex: string;
            if (Array.isArray(onChainBasket.creator)) {
              creatorHex = '0x' + onChainBasket.creator.map((byte: number) => 
                byte.toString(16).padStart(2, '0')
              ).join('');
            } else if (typeof onChainBasket.creator === 'string') {
              creatorHex = onChainBasket.creator;
            } else {
              creatorHex = String(onChainBasket.creator);
            }
            
            // Validate basket data before converting
            if (!onChainBasket.name || !onChainBasket.items || !Array.isArray(onChainBasket.items)) {
              console.warn(`[fetchAllOnChainBaskets] Basket ${i} has invalid data:`, {
                hasName: !!onChainBasket.name,
                hasItems: !!onChainBasket.items,
                itemsIsArray: Array.isArray(onChainBasket.items)
              });
              return null;
            }
            
            // Convert to frontend format
            const frontendBasket = onChainBasketToFrontend(
              onChainBasket as any,
              i,
              [], // tags - will be merged from localStorage if available
              undefined // snapshot - will be merged from localStorage if available
            );
            
            // Update creator with proper hex format
            frontendBasket.owner = creatorHex;
            
            // Validate the converted basket
            if (!frontendBasket.id || !frontendBasket.name || !frontendBasket.items) {
              console.warn(`[fetchAllOnChainBaskets] Basket ${i} conversion resulted in invalid basket:`, {
                id: frontendBasket.id,
                hasName: !!frontendBasket.name,
                hasItems: !!frontendBasket.items
              });
              return null;
            }
            
            console.log(`[fetchAllOnChainBaskets] ✓ Successfully fetched basket ${i}:`, {
              id: frontendBasket.id,
              name: frontendBasket.name,
              itemsCount: frontendBasket.items.length,
              owner: frontendBasket.owner
            });
            
            return frontendBasket;
          })
          .catch(error => {
            console.error(`[fetchAllOnChainBaskets] Error fetching basket ${i}:`, error);
            return null;
          })
      );
    }
    
    const baskets = (await Promise.all(fetchPromises)).filter((b): b is Basket => b !== null);
    
    // Deduplicate baskets by ID to prevent duplicates
    const uniqueBaskets = new Map<string, Basket>();
    baskets.forEach(basket => {
      if (basket && basket.id) {
        // If we already have this basket ID, log a warning
        if (uniqueBaskets.has(basket.id)) {
          console.warn(`[fetchAllOnChainBaskets] Duplicate basket ID detected: ${basket.id}. Keeping first occurrence.`);
        } else {
          uniqueBaskets.set(basket.id, basket);
        }
      }
    });
    
    const deduplicatedBaskets = Array.from(uniqueBaskets.values());
    console.log(`[fetchAllOnChainBaskets] Deduplicated to ${deduplicatedBaskets.length} unique baskets (from ${baskets.length} total)`);
    
    // Log all basket IDs for debugging
    console.log(`[fetchAllOnChainBaskets] Basket IDs:`, deduplicatedBaskets.map(b => ({
      id: b.id,
      name: b.name,
      itemsCount: b.items.length,
      owner: b.owner
    })));
    
    // Filter by owner if provided
    if (userAddress) {
      // Convert user address (SS58 format) to ActorId (hex format) for comparison
      // On-chain creators are stored as ActorId (hex), so we need to convert
      let userActorId: string | null = null;
      try {
        userActorId = actorIdFromAddress(userAddress).toLowerCase();
        console.log(`[fetchAllOnChainBaskets] User address ${userAddress} -> ActorId ${userActorId}`);
      } catch (error) {
        console.warn(`[fetchAllOnChainBaskets] Could not convert address to ActorId:`, error);
      }
      
      const filtered = deduplicatedBaskets.filter(b => {
        const ownerLower = b.owner.toLowerCase();
        // Match by ActorId format (on-chain creators are in hex/ActorId format)
        const matches = userActorId ? ownerLower === userActorId : false;
        if (!matches && userActorId) {
          console.log(`[fetchAllOnChainBaskets] Basket ${b.id} owner mismatch:`, {
            basketOwner: b.owner,
            userActorId,
            basketName: b.name,
            itemsCount: b.items.length
          });
        } else if (matches) {
          console.log(`[fetchAllOnChainBaskets] ✓ Basket ${b.id} matches user:`, {
            id: b.id,
            name: b.name,
            itemsCount: b.items.length,
            owner: b.owner
          });
        }
        return matches;
      });
      
      console.log(`[fetchAllOnChainBaskets] Filtered to ${filtered.length} baskets for user (from ${deduplicatedBaskets.length} total)`);
      return filtered;
    }
    
    return deduplicatedBaskets;
  } catch (error) {
    console.error('[fetchAllOnChainBaskets] Error:', error);
    throw error;
  }
}
