// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct PolymarketMirrorProgram;
impl sails_rs::client::Program for PolymarketMirrorProgram {}
pub trait PolymarketMirror {
    type Env: sails_rs::client::GearEnv;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PolymarketMirror
    for sails_rs::client::Actor<PolymarketMirrorProgram, E>
{
    type Env = E;
    fn basket_market(
        &self,
    ) -> sails_rs::client::Service<basket_market::BasketMarketImpl, Self::Env> {
        self.service(stringify!(BasketMarket))
    }
}
pub trait PolymarketMirrorCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        settler_role: ActorId,
        liveness_seconds: u64,
    ) -> sails_rs::client::PendingCtor<PolymarketMirrorProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> PolymarketMirrorCtors
    for sails_rs::client::Deployment<PolymarketMirrorProgram, E>
{
    type Env = E;
    fn new(
        self,
        settler_role: ActorId,
        liveness_seconds: u64,
    ) -> sails_rs::client::PendingCtor<PolymarketMirrorProgram, io::New, Self::Env> {
        self.pending_ctor((settler_role, liveness_seconds))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (settler_role: ActorId, liveness_seconds: u64) -> ());
}

pub mod basket_market {
    use super::*;
    pub trait BasketMarket {
        type Env: sails_rs::client::GearEnv;
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            index_at_creation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env>;
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env>;
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<BasketItem>,
            asset_kind: BasketAssetKind,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env>;
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env>;
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<ItemResolution>,
            payload: String,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env>;
        fn get_basket(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env>;
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env>;
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env>;
    }
    pub struct BasketMarketImpl;
    impl<E: sails_rs::client::GearEnv> BasketMarket for sails_rs::client::Service<BasketMarketImpl, E> {
        type Env = E;
        fn bet_on_basket(
            &mut self,
            basket_id: u64,
            index_at_creation_bps: u16,
        ) -> sails_rs::client::PendingCall<io::BetOnBasket, Self::Env> {
            self.pending_call((basket_id, index_at_creation_bps))
        }
        fn claim(&mut self, basket_id: u64) -> sails_rs::client::PendingCall<io::Claim, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn create_basket(
            &mut self,
            name: String,
            description: String,
            items: Vec<BasketItem>,
            asset_kind: BasketAssetKind,
        ) -> sails_rs::client::PendingCall<io::CreateBasket, Self::Env> {
            self.pending_call((name, description, items, asset_kind))
        }
        fn finalize_settlement(
            &mut self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::FinalizeSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn propose_settlement(
            &mut self,
            basket_id: u64,
            item_resolutions: Vec<ItemResolution>,
            payload: String,
        ) -> sails_rs::client::PendingCall<io::ProposeSettlement, Self::Env> {
            self.pending_call((basket_id, item_resolutions, payload))
        }
        fn get_basket(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetBasket, Self::Env> {
            self.pending_call((basket_id,))
        }
        fn get_basket_count(&self) -> sails_rs::client::PendingCall<io::GetBasketCount, Self::Env> {
            self.pending_call(())
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_positions(
            &self,
            user: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetPositions, Self::Env> {
            self.pending_call((user,))
        }
        fn get_settlement(
            &self,
            basket_id: u64,
        ) -> sails_rs::client::PendingCall<io::GetSettlement, Self::Env> {
            self.pending_call((basket_id,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(BetOnBasket (basket_id: u64, index_at_creation_bps: u16) -> Result<u128, String>);
        sails_rs::io_struct_impl!(Claim (basket_id: u64) -> Result<u128, String>);
        sails_rs::io_struct_impl!(CreateBasket (name: String, description: String, items: Vec<super::BasketItem>, asset_kind: super::BasketAssetKind) -> Result<u64, String>);
        sails_rs::io_struct_impl!(FinalizeSettlement (basket_id: u64) -> Result<(), String>);
        sails_rs::io_struct_impl!(ProposeSettlement (basket_id: u64, item_resolutions: Vec<super::ItemResolution>, payload: String) -> Result<(), String>);
        sails_rs::io_struct_impl!(GetBasket (basket_id: u64) -> Result<super::Basket, String>);
        sails_rs::io_struct_impl!(GetBasketCount () -> u64);
        sails_rs::io_struct_impl!(GetConfig () -> (ActorId,u64,));
        sails_rs::io_struct_impl!(GetPositions (user: ActorId) -> Vec<super::Position>);
        sails_rs::io_struct_impl!(GetSettlement (basket_id: u64) -> Result<super::Settlement, String>);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BasketItem {
    pub poly_market_id: String,
    pub poly_slug: String,
    pub weight_bps: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BasketAssetKind {
    Vara,
    Bet,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ItemResolution {
    pub item_index: u8,
    pub resolved: Outcome,
    pub poly_slug: String,
    pub poly_condition_id: Option<String>,
    pub poly_price_yes: u16,
    pub poly_price_no: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Outcome {
    YES,
    NO,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Basket {
    pub id: u64,
    pub creator: ActorId,
    pub name: String,
    pub description: String,
    pub items: Vec<BasketItem>,
    pub created_at: u64,
    pub status: BasketStatus,
    pub asset_kind: BasketAssetKind,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BasketStatus {
    Active,
    Settled,
    Closed,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub basket_id: u64,
    pub user: ActorId,
    pub shares: u128,
    pub claimed: bool,
    pub index_at_creation_bps: u16,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Settlement {
    pub basket_id: u64,
    pub proposer: ActorId,
    pub item_resolutions: Vec<ItemResolution>,
    pub payout_per_share: u128,
    pub payload: String,
    pub proposed_at: u64,
    pub challenge_deadline: u64,
    pub finalized_at: Option<u64>,
    pub status: SettlementStatus,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum SettlementStatus {
    Proposed,
    Finalized,
    Disputed,
}
